services:
  sqs-client-poc:
    build: .
    image: sqs-client-poc:latest
    container_name: sqs-client-poc
    restart: unless-stopped
    ports:
      - 3100:80
    command: ['nginx', '-g', 'daemon off;']
