/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CommandInput: typeof import('./../components/CommandInput.vue')['default']
    CommonEmpty: typeof import('./../components/CommonEmpty.vue')['default']
    CommonLoading: typeof import('./../components/CommonLoading.vue')['default']
    CommonTable: typeof import('./../components/CommonTable.vue')['default']
    GlobalHeader: typeof import('./../components/GlobalHeader/GlobalHeader.vue')['default']
    LoadingMask: typeof import('./../components/LoadingMask.vue')['default']
    MarkdownRender: typeof import('./../components/MarkdownRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLoginStatus: typeof import('./../components/GlobalHeader/components/UserLoginStatus.vue')['default']
  }
}
